site_name: Manuel Utilisateur AC LOG
site_url: https://arthur-dubaj2.github.io/docACLOG/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    
    - navigation.top
    - content.tab.links
    - toc.integrate
  
  icon:
    repo: fontawesome/brands/git-alt
  # Ajout des polices
  font:
    text: Roboto
    code: Roboto Mono

# Ajout des plugins Material
plugins:
  - search
  - minify:
      minify_html: true

extra_css:
  - style.css

nav:
  - Introduction: introduction.md
  - Installation: installation.md
  - Interface du logiciel: interface.md
  - Paramétrage initial: parametrage.md
  - Collaborateur et sécurité utilisateur: collabrateursSecurite.md
  - Clients:
      - Liste Clients: client/listeClients.md
      - Fiche Client: client/ficheClient.md
      
  - Produits:
      - Liste Produits: produits/listeProduits.md
      - Fiche Produit: produits/ficheProduits.md
      
  - Prestations:
      - Liste Prestation: prestations/listePrestations.md
      - Fiche Prestation: prestations/fichePrestations.md
  - Forfaits:
      - Liste Forfaits: forfaits/listeForfaits.md
      - Fiche Forfait: forfaits/ficheForfait.md
      
  - Chèques Cadeaux:
      - Liste Chèque Cadeau: chequeCadeaux/listeCheques.md
      - Fiche Chèque Cadeau: chequeCadeaux/ficheCheques.md
      
  - Fournisseurs:
      - Liste Fournisseurs: fournisseurs/listeFournisseurs.md
      - Fiche Fournisseur: fournisseurs/ficheFournisseur.md
      
  - Commandes Fournisseurs:
      - Liste Commande Fournisseur : cmdFournisseurs/listeCmdFour.md
      - Fiche Commande Fournisseur : cmdFournisseurs/ficheCmdFour.md
   

  - Gestion commerciale:
      - Devis: gestion/devis.md
      - Factures: gestion/facture.md
      - Bons de livraison: gestion/bdl.md
      - Avoirs: gestion/avoir.md
      - Commandes clients: gestion/commande.md
      - Règlements en attente: gestion/reglAtt.md
  - Stock:
      - Etat du stock : stock/etatStock.md
      - Entree de stock : stock/entreeStock.md
      - Sortie de stock : stock/sortieStock.md
  - Caisse:
      - Interface de Caisse : caisse/interfaceCaisse.md
      - Enregistrement d'une vente : caisse/enregVente.md
      - Modes de Paiement : caisse/modePaiement.md
      - Gestion des Tickets: caisse/gestionTickets.md
      - Acomptes et Commandes : caisse/acompteCommande.md
      - Gestion des avoirs et remboursements : caisse/remboursements.md
  - Clôture de caisse: cloture.md
  - Statistiques: stats.md
  - Import/Export: importExport.md
  - Export Comptable: exportComptable.md
  - Sauvegarde et restauration: sauvRestauration.md
  - Support Utilisateur: suppUtilisateur.md
  - Administration fiscale: adminFiscale.md
  - Annexes: annexes.md
  - Modules métiers spécifiques: modMetiers.md
  - Modules complémentaires: modComplem.md

